Repository National-Digital-Twin/IRIS-visualisation, pull requests merged in 2025-09, with the labels that each got.

#106 feature: (DPAV-1455) facilitate other EPC layers
  k8s/visualiser/base/deployment.yaml
  k8s/visualiser/base/vault/vaultAuth.yaml
  k8s/visualiser/base/vault/vaultStaticSecret.yaml
  scripts/config.index.ts
  src/app/components/map/map.component.ts
  src/app/core/services/layers/epc-layer.ts
  src/app/core/services/layers/epc.layer.ts
  src/app/core/services/layers/layer-factory.service.ts
  src/configurations/dev/config.json
  src/configurations/prod/config.json
  src/environments/environment.ts
Labels: feature

#107 feat(dpav-1684): added os roof data to advanced filters
  CHANGELOG.md
  src/app/containers/filter-panel/filter-panel.service.spec.ts
  src/app/containers/filter-panel/filter-panel.service.ts
  src/app/containers/main-filters/main-filters.component.ts
  src/app/core/enums/roof-aspect-area-direction.ts
  src/app/core/models/advanced-filters.model.ts
  src/app/core/models/filterable-building.model.ts
  src/app/core/services/filterable-building.service.ts
  src/app/core/services/utils.service.ts
Labels: documentation, feature

#113 bugfix: (DPAV-1487) remove lingering outlines when deselecting layers
  src/app/components/map/map.component.ts
Labels: fix

#114 feat: [NON-REQ] update base map
  src/app/components/map/map.component.ts
  src/app/components/minimap/minimap.component.ts
  src/app/core/services/map.service.ts
  src/configurations/dev/config.json
  src/configurations/prod/config.json
  transparent-proxy/proxy.conf.template
Labels: feature

#115 bugfix: revert - update basemap
  src/app/components/map/map.component.ts
  src/app/components/minimap/minimap.component.ts
  src/app/core/services/map.service.ts
  src/configurations/dev/config.json
  src/configurations/prod/config.json
  transparent-proxy/proxy.conf.template
Labels: fix

#120 feat(DPAV-1727): hide layers when buildings are shown
  .husky/pre-commit
  package-lock.json
  package.json
  src/app/components/map/map.component.html
  src/app/components/map/map.component.ts
  src/app/core/models/runtime-configuration.model.ts
  src/app/core/services/ui-state.service.ts
  src/app/core/tokens/cache.token.ts
  src/configurations/dev/config.json
  src/configurations/prod/config.json
  src/environments/environment.test.ts
  src/environments/environment.ts
Labels: feature

#121 fix(DFE-1729): only allow one map control to be open
  src/app/components/map/map.component.ts
Labels: fix

#125 feat(DPAV-1760): os ngd roof aspect ui tweak
  src/app/components/details-panel/details-panel.component.html
  src/app/components/details-panel/details-panel.component.ts
Labels: feature

#126 feature(DPAV-1731): remove commercial building ui tweak
  src/app/core/services/layers/epc.layer.ts
Labels: feature
