Repository National-Digital-Twin/IRIS-visualisation, pull requests merged in 2025-08, with the labels that each got.

#98 feat(DPAV-1452): toggling of future layers
  package-lock.json
  package.json
  src/app/components/map/map.component.html
  src/app/components/map/map.component.ts
  src/app/core/services/map.service.ts
  src/app/core/services/map.token.ts
  src/styles/main.scss
Labels: feature

#100 feat(OSPO): move to use of unprivileged nginx containers
  docker/Dockerfile
  k8s/transparent-proxy/base/deployment.yaml
  k8s/transparent-proxy/base/service.yaml
  k8s/visualiser/base/deployment.yaml
  k8s/visualiser/base/service.yaml
  package-lock.json
  transparent-proxy/Dockerfile
  transparent-proxy/README.md
  transparent-proxy/proxy.conf.template
Labels: documentation, feature

#101 feat(DPAV-1291): climate data layers added
  .github/workflows/oss-checker.yml
  .github/workflows/publish-github-release.yml
  .prettierignore
  src/app/components/legend/legend.component.html
  src/app/components/legend/legend.component.scss
  src/app/components/legend/legend.component.ts
  src/app/components/map/map.component.html
  src/app/components/map/map.component.ts
  src/app/core/config/layer-colors.config.ts
  src/app/core/services/climate-data.service.ts
  src/app/core/services/layers/base-layer.abstract.ts
  src/app/core/services/layers/climate-layer.abstract.ts
  src/app/core/services/layers/hot-summer-days.layer.ts
  src/app/core/services/layers/icing-days.layer.ts
  src/app/core/services/layers/layer-factory.service.ts
  src/app/core/services/layers/wind-driven-rain.layer.ts
  src/app/core/services/script-loader.service.ts
  src/app/core/services/ui-state.service.ts
  src/assets/js/popup-common.js
  src/assets/js/popup-wind-driven-rain.js
  src/styles/_mapbox.scss
  src/styles/main.scss
Labels: feature, actions
